name: Precipitations Forecast

on:
  schedule:
    - cron: "45 8 * * *"   # 10h45 France en heure d'été
    - cron: "0 11 * * *"   # 13h00 France en heure d'été

  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    env:
      UPDATER_REPO_TOKEN: ${{ secrets.UPDATER_REPO_TOKEN }}
      UPDATER_REPO_OWNER: ${{ secrets.UPDATER_REPO_OWNER }}
      UPDATER_REPO_NAME: ${{ secrets.UPDATER_REPO_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Execute script
        run: |
          python main.py
